version: '3'

services:
    app:
        build: ./docker/apache
        ports:
            - 8080:80
        volumes:
            - ./site:/var/www/html
        links:
            - db:postgres

    db:
        image: postgres:13.0 # set version to 9 if you encounter problems.
        volumes:
            - ./docker/data/postgres/logs:/var/log/postgresql
            - ./docker/data/postgres/data:/var/lib/postgresql/data
            - ./BDD-UNIVERS.sql:/docker-entrypoint-initdb.d/BDD-UNIVERS.sql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=changeme
            - POSTGRES_USER=postgres
            - POSTGRES_DB=BDD-UNIVERS

            
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres@local.int
            PGADMIN_DEFAULT_PASSWORD: changeme
            PG_DATABASE: BDD-UNIVERS
            PG_USER: postgres
            PG_PASSWORD: changeme
        volumes:
            - ./docker/pgadmin:/root/.pgadmin
        ports:
            - 8081:80
        links:
            - db:postgres